# Done to increase the memory available to gradle.
org.gradle.jvmargs=-Xmx1G
org.gradle.parallel=true

# Fabric Properties
	# https://fabricmc.net/develop
	# https://parchmentmc.org/docs/getting-started
	minecraft_version=1.21.3
	loader_version=0.16.7
	mappings_version=1.21:2024.06.23

# Mod Properties
	mod_version=1.3.9
	maven_group=com.mt1006.mocap
	archives_base_name=Mocap

# Dependencies
	fabric_version=0.106.1+1.21.3
