# Mod info
mod_name=Motion Capture
mod_jar_name=Mocap
mod_id=mocap
mod_group=net.mt1006.mocap
mod_author=mt1006
version=1.4-alpha-10
license=LGPL-3.0-only
homepage=https://modrinth.com/mod/motion-capture
source_url=https://github.com/mt1006/mc-mocap-mod
issue_tracker=https://github.com/mt1006/mc-mocap-mod/issues
mod_description=Allows you to record and replay player movements.

# Minecraft and Java
minecraft_version=26.1
java_version=25

# Requires
version_range_fabric=>=26.1
version_range_neoforge=[26.1,)

# Loaders
# https://github.com/FabricMC/fabric-loader/releases
# https://modrinth.com/mod/fabric-api/versions?c=release
# https://projects.neoforged.net/neoforged/neoforge
fabric_loader_version=0.18.5
fabric_api_version=0.144.3+26.1
neoforge_version=26.1.0.8-beta

# Gradle dependencies
# https://github.com/FabricMC/fabric-loom/releases
# https://projects.neoforged.net/neoforged/ModDevGradle
fabric_loom_version=1.15-SNAPSHOT
neoforge_moddev_version=2.0.141

# Gradle configuration
org.gradle.jvmargs=-Xmx3G
org.gradle.daemon=false
org.gradle.problems.report=false
