plugins
{
	id "net.neoforged.moddev" version "${neoforge_moddev_version}"
}

neoForge
{
	version = neoforge_version
	parchment
	{
		minecraftVersion = parchment_minecraft
		mappingsVersion = parchment_version
	}

	runs
	{
		client { client() }
		server { server() }
	}

	mods
	{
		"${mod_id}" { sourceSet sourceSets.main }
	}
}

repositories {
	maven { url 'https://maven.kosmx.dev/' }
	maven {url = "https://repo.redlance.org/public" }
}

dependencies {
	compileOnly("io.github.kosmx.emotes:emotesAPI:${emotesAPI_version}") {
		exclude group: 'com.google.guava', module: 'guava'
	}
}


processResources
{
	from(project.file("src/main/generated")) { duplicatesStrategy DuplicatesStrategy.EXCLUDE }
}